// One plain sentence per kind: what the cell is for.

export const KIND_ABOUT: Record<string, string> = {
  empty: 'Nothing yet. Pick what this cell should hold.',
  text: 'Words, headings and lists, with live values from other cells.',
  formula: 'A value worked out from other cells.',
  input: 'A field people fill in; other cells read what they enter.',
  button: 'Runs an action when clicked, like saving a record or changing a value.',
  image: 'A picture, uploaded or linked.',
  icon: 'A small symbol.',
  chart: 'Draws numbers as bars, lines or parts of a whole.',
  table: 'Rows of records people can search, sort and pick.',
  list: 'Items people add, edit and tick off.',
  calendar: 'A month of events; the day people pick is its value.',
  canvas: 'A surface to draw or sign on.',
  stat: 'A headline number and how it moved.',
  break: 'Starts a new page when the document is printed.',
  row: 'Holds cells side by side.',
  col: 'Holds cells one under another.',
  tabs: 'Panels behind a tab bar; one shows at a time. Its value is the open tab’s title.',
  accordion: 'Sections that fold open and shut. Its value is the list of open titles.',
  collapsible: 'A heading that folds the cells under it. Its value is true while open.',
  panel: 'One tab or section: a title and the cells under it.',
  diagram: 'Shapes, text and arrows that stay joined when you move them.',
  data: 'A value for formulas and buttons to use. Readers never see it.',
  timer: 'Ticks every so often (or once) while the document is open in Live, and runs its tick handler.',
  fetch: 'JSON from a web address, fetched by the server; formulas read it by name.',
};
