#!/usr/bin/env bash
# Regenerates the evidence in this folder from a fresh server with empty data:
#   TMPDIR=/tmp/ev CHROME=/path/to/chrome docs/showcase/events/shoot.sh
# Builds, starts edgy on port 8796, creates the "Market stall" template and the
# small documents next to this script, drives the events that matter, saves the
# screenshots and writes what each run printed to events.txt.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"
S=goal-loop/scripts
P=.claude/goal-loop
export CDP_PANE=".desk, .home, .records"   # the app scrolls in these, not the page
OUT=docs/showcase/events
WORK="${TMPDIR:-/tmp}/events-shots"
PORT=8796
URL="http://127.0.0.1:$PORT"
LOG="$OUT/events.txt"
mkdir -p "$WORK"
bash $P/serve.sh fresh $PORT "$WORK/data" >/dev/null || exit 1

new() { node $OUT/mk.mjs "$URL" "$1"; }
shot() { node $S/cdp.mjs shot "$@"; echo "   (exit $?)"; }
values() { curl -s "$URL/api/docs/$1/read" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8")); const keep=process.argv.slice(1); console.log("   values: " + JSON.stringify(Object.fromEntries(Object.entries(d.values).filter(([k])=>!keep.length||keep.includes(k)))))' "${@:2}"; }
outline() { curl -s "$URL/api/docs/$1/read" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8")); const re=new RegExp(process.argv[1]); console.log(d.outline.split("\n").filter(l=>re.test(l)).map(l=>"   "+l).join("\n"))' "$2"; }
say() { echo; echo "── $* ──"; }

STALL=$(curl -s -XPOST "$URL/api/docs" -H 'content-type: application/json' -d '{"template":"events"}' | node -pe 'JSON.parse(require("fs").readFileSync(0)).id')
LAB=$(new $OUT/lab.json)
TIMER=$(new $OUT/timer.json)
CONSENT=$(new $OUT/consent.json)
ASK=$(new $OUT/ask.json)
SLOW=$(curl -s -XPOST "$URL/api/docs" -H 'content-type: application/json' -d '{"title":"Slow rate","root":["col",["text",{"size":"hug"},"# Slow rate"],["fetch",{"name":"slow","label":"Rate from a slow service"},"/api/demo/slow?ms=4000"],["text",{"size":"hug"},"Status: {{(status slow)}}"]]}' | node -pe 'JSON.parse(require("fs").readFileSync(0)).id')
FAILS=$(curl -s -XPOST "$URL/api/docs" -H 'content-type: application/json' -d '{"title":"Fetches that fail","root":["col",["text",{"size":"hug"},"# Fetches that fail"],["fetch",{"name":"down","label":"A service that is down","on":{"fail":["set!","why","$message"]}},"/api/demo/fail"],["fetch",{"name":"gone","label":"An address that does not exist","on":{"fail":["set!","why2","$message"]}},"https://unreachable.invalid/rate.json"],["text",{"size":"hug"},"down: {{why}} \u00b7 gone: {{why2}} \u00b7 status {{(status down)}} / {{(status gone)}}"],["data",{"name":"why"},""],["data",{"name":"why2"},""]]}' | node -pe 'JSON.parse(require("fs").readFileSync(0)).id')

{
echo "Evidence for the events goal, regenerated by shoot.sh on $(date -u +%Y-%m-%dT%H:%MZ) against a fresh server with empty data."
echo "Documents: stall $STALL, lab $LAB, timer $TIMER, consent $CONSENT, ask $ASK, slow $SLOW, fails $FAILS"

say "D1 the document opening: Edit runs nothing, each open in Live runs open once"
shot "$URL/d/$LAB?view=edit" "$WORK/lab-edit.png" --size 1440x900 --wait 3000 >/dev/null
values "$LAB" opens
for i in 1 2 3; do shot "$URL/d/$LAB?view=live" "$WORK/lab-open-$i.png" --size 1440x900 --wait 2500 >/dev/null; done
values "$LAB" opens

say "D2 D3 D6 D7 D8 D9 the lab, used in Live: checkbox, clicks, rows, emit, custom actions, loop guard, undo, stop"
shot "$URL/d/$LAB?view=live" "$OUT/activity.png" --size 1440x900 --js "$(cat $OUT/lab-run.js)" --wait 800
values "$LAB" agree status flips clicks doubles lastClick lastDouble a b hello spin spun ticks poll
outline "$LAB" 'broken|greet|^action|document on'

say "D4 a timer every 2 s: ~7 s in Live, then Home"
shot "$URL/d/$TIMER?view=live" "$WORK/timer.png" --size 1440x900 --js "$(cat $OUT/timer-run.js)" --wait 300
values "$TIMER"

say "D5 fetch: the loading state, then the failures"
shot "$URL/d/$SLOW?view=live" "$OUT/fetch-loading.png" --size 900x500 --wait 1500 --js "document.querySelector('.kfetch')?.textContent"
shot "$URL/d/$FAILS?view=live" "$OUT/fetch-error.png" --size 900x560 --wait 13000 --js "[...document.querySelectorAll('.kfetch')].map(e=>e.textContent).join(' | ')"
values "$FAILS" why why2
outline "$FAILS" 'fetch'

say "D7 a missing action is an error in the cell and the outline"
shot "$URL/d/$LAB?view=edit" "$OUT/action-error.png" --size 1100x700 --wait 2500 \
  --js "(()=>{const b=[...document.querySelectorAll('.kind-button')].find(e=>e.textContent.includes('Broken')); b.scrollIntoView({block:'center'}); return b.querySelector('.cell-error')?.textContent})()"

say "D11 attaching a handler with presets and Blocks only (clicks), desktop, phone, dark"
shot "$URL/d/$CONSENT?view=edit" "$OUT/events-part.png" --size 1440x900 --js "$(cat $OUT/d11.js)" --wait 600
values "$CONSENT" agree status
CONSENT2=$(new $OUT/consent.json)
shot "$URL/d/$CONSENT2?view=edit" "$OUT/events-part-phone.png" --size 390x844 --mobile --js "$(cat $OUT/d11.js)" --wait 600
values "$CONSENT2" agree status
CONSENT3=$(new $OUT/consent.json)
shot "$URL/d/$CONSENT3?view=edit" "$OUT/events-part-dark.png" --size 1440x900 --dark --js "$(cat $OUT/d11.js)" --wait 600
values "$CONSENT3" agree status

say "D12 Ask AI (offline composer), one sentence per family, applied as an agent"
node $OUT/ask.mjs "$URL" "$ASK"

say "D13 an agent attaches a handler with ops; the outline shows it"
curl -s -XPOST "$URL/api/docs/$ASK/ops" -H 'content-type: application/json' \
  -d '{"actor":{"kind":"agent","name":"Claude"},"ops":[["set","price","on.change",["set!","note",["str","price was ",["fmt","$was","number"]]]]]}' >/dev/null
outline "$ASK" 'input:number price'

say "G3 the Market stall, used"
shot "$URL/d/$STALL?view=live" "$OUT/stall-run.png" --size 1440x900 --js "$(cat $OUT/stall-run.js)" --wait 600
values "$STALL" visits orders-today last-order cart setup warn
} 2>&1 | tee "$LOG"

# ── the showcase at every size, in dark, and on paper ──
shot "$URL/d/$STALL?view=live" "$OUT/desktop.png" --size 1440x900 --full --wait 3000 >/dev/null
shot "$URL/d/$STALL?view=live" "$OUT/desktop-dark.png" --size 1440x900 --dark --wait 3000 >/dev/null
shot "$URL/d/$STALL?view=live" "$OUT/tablet.png" --size 820x1180 --wait 3000 >/dev/null
shot "$URL/d/$STALL?view=live" "$OUT/phone.png" --size 390x844 --mobile --wait 3000 >/dev/null
shot "$URL/d/$STALL?view=edit" "$OUT/edit.png" --size 1440x900 --wait 3000 >/dev/null
shot "$URL/d/$STALL?view=page" "$OUT/page.png" --size 1440x900 --full --wait 3000 >/dev/null
node $S/cdp.mjs pdf "$URL/d/$STALL?view=page" "$OUT/market-stall.pdf" --wait 3000 >/dev/null
curl -s "$URL/api/guide" | node -e 'const g=require("fs").readFileSync(0,"utf8"); const a=g.indexOf("## Events"); const b=g.indexOf("## Ops"); console.log(g.slice(a,b).trim())' > "$OUT/guide.txt"
bash $P/serve.sh stop $PORT >/dev/null
echo "done: $OUT"
