// Starting points, written in the same notation an agent uses.

import type { Json } from './types';

export interface Template {
  id: string;
  title: string;
  about: string;
  meta?: Record<string, Json>;
  root: Json;
  /** Sample records the template's cells read, saved into each collection that is still empty. */
  data?: Record<string, Record<string, Json>[]>;
}

const label = { fg: 'muted', size: 13 };
const card = { bg: 'sunken', radius: 12, pad: 8 };

const line = (what: string, qty: number, price: number): Json => [
  'row', { size: 'hug', style: { border: 'b', stack: 'never' } },
  ['input', { type: 'text', value: what, placeholder: 'Describe the work', size: 3 }],
  ['input', { type: 'number', value: qty, min: 0, style: { align: 'end' } }],
  ['input', { type: 'number', value: price, min: 0, step: 5, style: { align: 'end' } }],
  ['formula', { format: 'currency', style: { align: 'end', valign: 'center' } }, ['*', ['sib', 1], ['sib', 2]]],
];

const quote: Template = {
  id: 'quote',
  title: 'Quote',
  about: 'Line items that add up, a discount slider, and a button that saves each quote.',
  meta: { currency: 'EUR' },
  root: ['col',
    ['row', { size: 'hug' },
      ['col', { size: 2 },
        ['text', { style: { size: 34, weight: 750 } }, 'Quote'],
        ['text', { style: { fg: 'muted' } }, 'Prepared for **{{(default client "your client")}}** on {{date | date}}']],
      ['col',
        ['icon', { style: { fg: 'accent', size: 30, align: 'end' } }, 'anchor'],
        ['text', { style: { align: 'end', fg: 'muted', size: 13 } }, '**Northwind Studio**\n12 Harbour Lane, Bristol']]],
    ['row', { size: 'hug' },
      ['input', { name: 'client', type: 'text', label: 'Client', value: 'Ada Lovelace', size: 2 }],
      ['input', { name: 'date', type: 'date', label: 'Date', value: '2026-09-30' }],
      ['input', { name: 'valid', type: 'number', label: 'Valid for (days)', value: 30, min: 1 }]],
    ['row', { size: 'hug', style: { fg: 'muted', size: 12, weight: 600, border: 'b', stack: 'never' } },
      ['text', { size: 3 }, 'Item'],
      ['text', { style: { align: 'end' } }, 'Qty'],
      ['text', { style: { align: 'end' } }, 'Unit price'],
      ['text', { style: { align: 'end' } }, 'Amount']],
    ['col', { name: 'lines', size: 'hug' },
      line('Brand identity', 1, 2400),
      line('Website design, per page', 6, 380),
      line('Photography day', 2, 650)],
    ['row', { size: 'hug' },
      ['col', { size: 3 },
        ['row', { size: 'hug' },
          ['button', { size: 'hug', variant: 'soft', do: ['dup!', ['child', 'lines', -1]] }, 'Add a line'],
          ['button', { size: 'hug', variant: 'ghost', do: ['remove!', ['child', 'lines', -1]], hidden: ['<=', ['len', '$lines'], 1] }, 'Remove the last'],
          ['empty']],
        ['text', { style: label }, 'Valid until {{(date+ date valid) | date}}.']],
      ['col', { size: 2 },
        ['row', 'Subtotal', ['formula', { name: 'subtotal', format: 'currency', style: { align: 'end' } }, ['sum', ['column', '$lines', 3]]]],
        ['row',
          ['input', { name: 'discount', type: 'slider', min: 0, max: 30, step: 1, value: 10, label: 'Discount {{discount}}%' }],
          ['formula', { name: 'off', format: 'currency', style: { align: 'end', valign: 'end', fg: 'live' } }, ['-', ['*', '$subtotal', ['/', '$discount', 100]]]]],
        ['row', 'VAT 19%', ['formula', { name: 'vat', format: 'currency', style: { align: 'end' } }, ['*', ['+', '$subtotal', '$off'], 0.19]]],
        ['row', { style: { border: 't', weight: 700, size: 18 } },
          'Total',
          ['formula', { name: 'total', format: 'currency', style: { align: 'end' } }, ['+', '$subtotal', '$off', '$vat']]]]],
    ['row', { size: 'hug', style: { ...card, pad: 6 } },
      ['button', { do: ['insert!', 'quotes', { client: '$client', date: '$date', items: ['len', '$lines'], total: '$total' }] }, 'Save this quote'],
      ['text', { size: 3, style: { fg: 'muted', valign: 'center' } },
        '{{(len (rows "quotes"))}} saved so far, worth {{(sum (column (rows "quotes") "total")) | currency}}.']],
  ],
};

const savings: Template = {
  id: 'savings',
  title: 'Savings plan',
  about: 'Sliders feed a function held in a cell; a chart and three totals follow.',
  root: ['col', { style: { gap: 6 } },
    ['text', { size: 'hug', style: { size: 30, weight: 750 } }, 'Savings plan'],
    ['text', { size: 'hug', style: { fg: 'muted' } }, 'Move the sliders. Everything on the right follows.'],
    ['row', { style: { gap: 10 } },
      ['col', { size: 2, style: card },
        ['input', { name: 'monthly', type: 'slider', min: 50, max: 2000, step: 50, value: 400, label: 'Every month I save {{monthly | currency}}' }],
        ['input', { name: 'years', type: 'slider', min: 1, max: 40, step: 1, value: 15, label: 'For {{years}} years' }],
        ['input', { name: 'rate', type: 'slider', min: 0, max: 12, step: 0.5, value: 6, label: 'Earning {{rate}}% a year' }],
        ['input', { name: 'start', type: 'number', min: 0, step: 500, value: 5000, label: 'Starting with' }],
        ['formula', { name: 'balance', hidden: true },
          ['fn', ['y'],
            ['let', ['r', ['/', '$rate', 1200], 'n', ['*', '$y', 12]],
              ['if', ['=', '$r', 0],
                ['+', '$start', ['*', '$monthly', '$n']],
                ['+', ['*', '$start', ['^', ['+', 1, '$r'], '$n']],
                  ['*', '$monthly', ['/', ['-', ['^', ['+', 1, '$r'], '$n'], 1], '$r']]]]]]]],
      ['col', { size: 3 },
        ['row', { size: 'hug' },
          ['col',
            ['text', { style: label }, 'After {{years}} years'],
            ['formula', { name: 'final', format: 'currency', style: { size: 24, weight: 750, fg: 'accent' } }, ['balance', '$years']]],
          ['col',
            ['text', { style: label }, 'You put in'],
            ['formula', { name: 'paid', format: 'currency', style: { size: 20, weight: 600 } }, ['+', '$start', ['*', '$monthly', '$years', 12]]]],
          ['col',
            ['text', { style: label }, 'Growth'],
            ['formula', { name: 'growth', format: 'currency', style: { size: 20, weight: 600, fg: 'live' } }, ['-', '$final', '$paid']]]],
        ['chart', { type: 'area', label: 'Balance by year' },
          ['map', { label: ['str', '$it'], value: ['round', ['balance', '$it']] }, ['range', 0, ['+', '$years', 1]]]],
        ['text', { size: 'hug', style: label },
          'Growth makes up {{(/ growth final) | percent}} of the final amount.{{(if (> rate 8) " A return above 8% a year is optimistic." "")}}']]],
  ],
};

const feedback: Template = {
  id: 'feedback',
  title: 'Feedback form',
  about: 'A form that saves answers to a collection, next to live results drawn from it.',
  root: ['row', { style: { gap: 12 } },
    ['col',
      ['text', { size: 'hug', style: { size: 26, weight: 750 } }, 'How was your visit?'],
      ['input', { name: 'who', type: 'text', label: 'Your name', placeholder: 'Name', size: 'hug' }],
      ['input', { name: 'stars', type: 'rating', label: 'Rating', value: 4, max: 5, size: 'hug' }],
      ['input', { name: 'topic', type: 'select', label: 'What is this about?', options: ['list', 'Food', 'Service', 'Atmosphere'], value: 'Food', size: 'hug' }],
      ['input', { name: 'comment', type: 'textarea', label: 'Anything to add?', placeholder: 'Optional' }],
      ['button', {
        size: 'hug',
        do: ['do',
          ['insert!', 'feedback', { name: ['default', '$who', 'Anonymous'], rating: '$stars', topic: '$topic', comment: '$comment' }],
          ['set!', 'who', ''],
          ['set!', 'comment', '']],
      }, 'Send feedback']],
    ['col', { style: card },
      ['text', { size: 'hug', style: { size: 18, weight: 650 } }, 'Answers so far'],
      ['row', { size: 'hug' },
        ['col',
          ['formula', { name: 'answers', style: { size: 30, weight: 750 } }, ['len', ['rows', 'feedback']]],
          ['text', { style: label }, 'answers']],
        ['col',
          ['formula', {
            name: 'mean', format: '0.0',
            style: { size: 30, weight: 750, fg: ['cond', ['=', '$answers', 0], 'faint', ['>=', '$mean', 4], 'live', ['>=', '$mean', 3], 'warn', 'bad'] },
          }, ['avg', ['column', ['rows', 'feedback'], 'rating']]],
          ['text', { style: label }, 'average rating']]],
      ['chart', { type: 'bar', label: 'How many gave each rating' },
        ['map', ['fn', ['s'], { label: ['str', '$s', '★'], value: ['len', ['where', ['rows', 'feedback'], 'rating', '$s']] }], ['range', 1, 6]]],
      ['table', ['map', { name: ['get', '$it', 'name'], rating: ['get', '$it', 'rating'], topic: ['get', '$it', 'topic'], when: ['fmt', ['get', '$it', 'at'], 'ago'] },
        ['take', 5, ['reverse', ['rows', 'feedback']]]]]],
  ],
};

export const tour: Template = {
  id: 'tour',
  title: 'Start here',
  about: 'A short tour you can poke at.',
  root: ['col', { style: { gap: 10 } },
    ['row', { size: 'hug' },
      ['col', { size: 3 },
        ['text', { style: { size: 34, weight: 750, line: 1.1 } }, 'Every document starts as one cell'],
        ['text', { style: { fg: 'muted', size: 16 } },
          'Select a cell and press a **+** on its edge to split it. Hold Shift to select several, then merge them. A cell can hold text, an input, a formula, a picture, an icon, a button, a chart or a table.']],
      ['image', { fit: 'contain', alt: 'One cell dividing into two', size: 2 }, '/art/division.svg']],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['col', { style: card },
        ['text', '**Cells hold values**'],
        ['input', { name: 'apples', type: 'slider', min: 0, max: 24, value: 6, label: '{{apples}} apples' }],
        ['input', { name: 'each', type: 'number', value: 0.45, step: 0.05, min: 0, label: 'Price of one' }]],
      ['col', { style: { ...card, bg: 'accent-soft' } },
        ['text', '**Formulas read other cells**'],
        ['formula', { name: 'cost', format: 'currency', style: { size: 34, weight: 750, fg: 'accent' } }, ['*', '$apples', '$each']],
        ['text', { style: label }, 'This one is `(* apples each)`. Select it to see what it reads.']],
      ['col', { style: card },
        ['text', '**Buttons change things**'],
        ['row', { size: 'hug' },
          ['button', { size: 'hug', do: ['set!', 'apples', ['+', '$apples', 1]] }, 'Add an apple'],
          ['button', { size: 'hug', variant: 'ghost', do: ['set!', 'apples', 0] }, 'Eat them all']],
        ['text', { style: label }, '{{(if (= apples 0) "The basket is empty." (str apples " in the basket, " (fmt cost "currency") " to pay."))}}']]],
    ['row', { size: 'hug' },
      ['icon', { style: { fg: 'agent', size: 26, valign: 'start' } }, 'sparkles'],
      ['text', { size: 12 },
        '**An agent can work here with you.** Everything you do is a small instruction such as `(split c4 row)`, and an agent sends the same instructions. Open **Activity** to watch them arrive, or to leave the agent a message.']],
    ['text', { size: 'hug', style: label },
      'Enter edits a cell. / changes what it holds. ⌥ with an arrow splits. ⌘M merges. ⌫ clears, then removes. ⌘Z undoes.'],
  ],
};


const cost = (what: string, qty: number, each: number): Json => [
  'row', { size: 'hug', style: { border: 'b', stack: 'never' } },
  ['input', { type: 'text', value: what, size: 2.4 }],
  ['input', { type: 'number', value: qty, min: 0, style: { align: 'end' } }],
  ['input', { type: 'number', value: each, min: 0, step: 10, style: { align: 'end' } }],
  ['formula', { format: 'currency', style: { align: 'end', valign: 'center' } }, ['*', ['sib', 1], ['sib', 2]]],
];

const showcase: Template = {
  id: 'showcase',
  title: 'Team offsite',
  about: 'Every kind of cell at work: stats, a checklist, a calendar, a budget, a searchable table, a signature, and pages to print.',
  meta: { currency: 'EUR', page: 'A4', orientation: 'portrait', margin: 14, footer: 'title' },
  root: ['col', { style: { gap: 8 } },
    ['row', { size: 'hug' },
      ['col', { size: 3 },
        ['text', { style: { size: 32, weight: 750, line: 1.1 } }, 'Team offsite, Lisbon'],
        ['text', { style: { fg: 'muted' } }, 'Three days for **{{people}} people**, {{(days (today) start)}} days from today. Everything below is live: tick, type, pick a day.']],
      ['icon', { size: 'hug', style: { fg: 'accent', size: 34, align: 'end' } }, 'plane']],
    ['row', { size: 'hug', style: { gap: 8 } },
      ['stat', { name: 'spent', label: 'Budget used', format: 'currency', icon: 'wallet', compare: ['*', '$budget', 0.8], trend: ['list', 2100, 3400, 4800, 6100, '$total'] }, '$total'],
      ['stat', { name: 'left', label: 'Still to spend', format: 'currency', icon: 'piggy-bank' }, ['-', '$budget', '$total']],
      ['stat', { name: 'ready', label: 'Prep done', format: 'percent', icon: 'check', compare: 0.25 }, ['/', ['count-if', ['get', '$it', 'done'], '$todo'], ['max', 1, ['len', '$todo']]]]],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['col', { style: { bg: 'sunken', radius: 12, pad: 6 } },
        ['list', { name: 'todo', type: 'check', label: 'Before we go' },
          { text: 'Book flights', done: true }, { text: 'Reserve the venue', done: true }, 'Order team t-shirts', 'Plan the Thursday dinner', 'Share the packing list'],
        ['list', { type: 'bullet', label: 'Bring' }, 'Laptop and charger', 'Comfortable shoes', 'A rain jacket']],
      ['col', { size: 1.4, style: { bg: 'sunken', radius: 12, pad: 6 } },
        ['calendar', { name: 'cal', label: 'October', value: '2026-10-14' },
          ['concat',
            ['list',
              { date: '$start', end: ['date+', '$start', 2], title: 'Offsite', color: 'accent' },
              { date: '2026-10-07', title: 'Venue deposit', color: 'warn' },
              { date: '2026-10-21', title: 'Retro', color: 'live' }],
            ['rows', 'offsite-events']]],
        ['row', { size: 'hug', style: { gap: 6 } },
          ['input', { name: 'what', type: 'text', placeholder: 'Add an event on the picked day', size: 3 }],
          ['button', { size: 'hug', variant: 'soft', do: ['do', ['insert!', 'offsite-events', { date: ['default', '$cal', ['today']], title: ['default', '$what', 'Something'] }], ['set!', 'what', '']] }, 'Add']]]],
    ['break'],
    ['text', { size: 'hug', style: { size: 22, weight: 700 } }, 'Budget'],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['input', { name: 'people', type: 'slider', min: 4, max: 40, value: 14, label: '{{people}} people' }],
      ['input', { name: 'budget', type: 'number', value: 12000, step: 500, label: 'Budget' }],
      ['input', { name: 'start', type: 'date', value: '2026-10-14', label: 'First day' }]],
    ['row', { size: 'hug', style: { fg: 'muted', size: 12, weight: 600, border: 'b', stack: 'never' } },
      ['text', { size: 2.4 }, 'Item'],
      ['text', { style: { align: 'end' } }, 'Qty'], ['text', { style: { align: 'end' } }, 'Each'], ['text', { style: { align: 'end' } }, 'Amount']],
    ['col', { name: 'costs', size: 'hug' },
      cost('Flights', 14, 240),
      cost('Hotel nights', 28, 95),
      cost('Venue, three days', 3, 600),
      cost('Dinner on Thursday', 14, 45)],
    ['row', { size: 'hug' },
      ['button', { size: 'hug', variant: 'ghost', do: ['dup!', ['child', 'costs', -1]] }, 'Add a cost'],
      ['text', { style: { align: 'end', weight: 700, size: 18 } }, 'Total {{total | currency}}'],
      ['formula', { name: 'total', hidden: true, format: 'currency' }, ['sum', ['column', '$costs', 3]]]],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['chart', { type: 'donut', label: 'Where the money goes' },
        ['map', { label: ['nth', '$it', 0], value: ['nth', '$it', 3] }, '$costs']],
      ['chart', { type: 'meter', label: 'Of the budget', max: '$budget', format: 'currency' }, '$total']],
    ['table', { name: 'roster', label: 'Who is coming', columns: [{ key: 'name', label: 'Name' }, { key: 'team', label: 'Team' }, { key: 'city', label: 'From' }, { key: 'nights', label: 'Nights', format: 'int' }, { key: 'diet', label: 'Diet' }] },
      ['list',
        { name: 'Ada Lovelace', team: 'Engineering', city: 'London', nights: 3, diet: 'Vegetarian' },
        { name: 'Grace Hopper', team: 'Engineering', city: 'New York', nights: 3, diet: '' },
        { name: 'Katherine Johnson', team: 'Research', city: 'Hampton', nights: 2, diet: 'Vegan' },
        { name: 'Alan Turing', team: 'Research', city: 'Manchester', nights: 3, diet: '' },
        { name: 'Hedy Lamarr', team: 'Design', city: 'Vienna', nights: 2, diet: 'No nuts' },
        { name: 'Margaret Hamilton', team: 'Engineering', city: 'Boston', nights: 3, diet: '' },
        { name: 'Edsger Dijkstra', team: 'Research', city: 'Rotterdam', nights: 1, diet: 'Vegetarian' },
        { name: 'Radia Perlman', team: 'Platform', city: 'Seattle', nights: 3, diet: '' },
        { name: 'Barbara Liskov', team: 'Platform', city: 'Boston', nights: 2, diet: 'Gluten free' },
        { name: 'Frances Allen', team: 'Platform', city: 'Peru, NY', nights: 3, diet: '' }]],
    ['break'],
    ['text', { size: 'hug', style: { size: 22, weight: 700 } }, 'Sign-off'],
    ['text', { size: 'hug', style: { fg: 'muted' } }, 'The budget owner signs here. The note below changes once there is a signature.'],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['canvas', { name: 'signature', label: 'Sign here', size: 2 }],
      ['col',
        ['input', { name: 'signer', type: 'text', label: 'Name', value: 'Ada Lovelace' }],
        ['text', { style: { fg: ['if', ['empty?', '$signature'], 'warn', 'live'], weight: 600 } },
          '{{(if (empty? signature) "Not signed yet" (str "Signed by " signer))}}']]]],
};


// ── data tables and typography ──

const heading: Json = { font: 'fraunces', size: 26, weight: 700, line: 1.2, tracking: -0.01 };
const note: Json = { fg: 'muted', size: 13 };
const eyebrow: Json = { size: 11.5, weight: 650, case: 'upper', tracking: 0.08, fg: 'muted' };

const invoice = (client: string, project: string, status: string, due: string, amount: number): Record<string, Json> => ({ client, project, status, due, amount });

const project = (name: string, lead: string, progress: number, onTrack: boolean, rating: number, site: string, hours: number, budget: number): Json =>
  ({ project: name, lead, progress, onTrack, rating, site, hours, budget });

const tables: Template = {
  id: 'tables',
  title: 'Studio billing',
  about: 'Data tables at work: invoices grouped by status with buttons on every row, projects typed into the table, totals, and a house style of fonts.',
  meta: { currency: 'EUR', page: 'A4', orientation: 'portrait', margin: 14, footer: 'title', font: 'inter', headFont: 'fraunces' },
  data: {
    'studio-invoices': [
      invoice('Acme Foods', 'Packaging refresh', 'Paid', '2026-10-03', 4200),
      invoice('Lumen Health', 'Patient app, phase 1', 'Paid', '2026-10-09', 7800),
      invoice('Harbor & Co', 'Annual report', 'Sent', '2026-10-21', 3150),
      invoice('Acme Foods', 'Spring campaign', 'Sent', '2026-10-28', 2600),
      invoice('Northfield School', 'Wayfinding signs', 'Overdue', '2026-09-26', 1900),
      invoice('Kite Bikes', 'Brand guidelines', 'Overdue', '2026-09-30', 5400),
      invoice('Lumen Health', 'Patient app, phase 2', 'Draft', '2026-11-14', 9600),
      invoice('Orbit Coffee', 'Menu boards', 'Sent', '2026-11-02', 1250),
      invoice('Harbor & Co', 'Website copy', 'Draft', '2026-11-20', 2300),
      invoice('Kite Bikes', 'Trade show stand', 'Paid', '2026-10-15', 3800),
    ],
  },
  root: ['col', { style: { gap: 10 } },
    ['row', { size: 'hug' },
      ['col', { size: 4 },
        ['text', { style: eyebrow }, 'Northwind Studio · Q4 2026'],
        ['text', { style: { font: 'fraunces', size: 40, weight: 700, line: 1.06, tracking: -0.02 } }, 'Billing and projects'],
        ['text', { style: { font: 'source-serif', size: 17, line: 1.55, fg: 'muted' } },
          'Every invoice and project in one place. Tick invoices to total them, fold the groups, settle one from its row, and type straight into the project table.']],
      ['icon', { size: 'hug', style: { fg: 'accent', size: 34 } }, 'receipt']],
    ['row', { size: 'hug', style: { gap: 8 } },
      ['stat', { name: 'billed', label: 'Billed this quarter', format: 'currency', icon: 'banknote', trend: ['list', 18400, 23900, 31200, '$billed'] }, ['sum', ['column', '$invoices', 'amount']]],
      ['stat', { name: 'owed', label: 'Still owed', format: 'currency', icon: 'wallet', better: 'down', compare: 26000 },
        ['sum-by', ['get', '$it', 'amount'], ['filter', ['!=', ['get', '$it', 'status'], 'Paid'], '$invoices']]],
      ['stat', { name: 'picked', label: '{{(len (selected invoices))}} picked', format: 'currency', icon: 'circle-check' },
        ['sum-by', ['get', '$it', 'amount'], ['selected', 'invoices']]]],
    ['text', { size: 'hug', style: heading }, 'Invoices'],
    ['text', { size: 'hug', style: note }, 'Grouped by status. Tick rows to total them; the buttons on each row change the saved record, draft a reminder, or delete it.'],
    ['table', {
      name: 'invoices', label: 'Invoices', group: 'status', select: 'many', stripes: true, header: 'filled',
      columns: [
        { key: 'client', label: 'Client', width: 160, bold: true },
        { key: 'project', label: 'Project', width: 180 },
        { key: 'status', label: 'Status', show: 'badge', colors: { Paid: 'live', Sent: 'accent', Overdue: 'bad', Draft: 'warn' } },
        { key: 'due', label: 'Due', format: 'date' },
        { key: 'amount', label: 'Amount', format: 'currency', align: 'end', total: 'sum' },
      ],
      actions: [
        { label: 'Paid', icon: 'check', variant: 'soft', do: ['update!', 'studio-invoices', ['get', '$row', 'id'], { status: 'Paid' }] },
        { label: '', icon: 'mail', variant: 'ghost',
          do: ['set!', 'reminder', ['str', 'Hi ', ['get', '$row', 'client'], ', a reminder that the invoice for ', ['get', '$row', 'project'], ' (', ['fmt', ['get', '$row', 'amount'], 'currency'], ') is due ', ['fmt', ['get', '$row', 'due'], 'date'], '. Thank you!']] },
        { label: '', icon: 'trash-2', variant: 'ghost', confirm: 'Delete this invoice?', do: ['delete!', 'studio-invoices', ['get', '$row', 'id']] },
      ],
    }, ['rows', 'studio-invoices']],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['input', { name: 'reminder', type: 'textarea', label: 'Reminder to send', placeholder: 'Press the envelope on a row to draft one', size: 2 }],
      ['col', { style: { bg: 'sunken', radius: 12, pad: 14, gap: 4 } },
        ['text', { style: eyebrow }, 'Picked'],
        ['text', { style: { font: 'fraunces', size: 30, weight: 700, line: 1.1 } }, '{{picked | currency}}'],
        ['text', { style: note }, '{{(len (selected invoices))}} of {{(len invoices)}} invoices. Other cells read them with (selected invoices).']]],
    ['break'],
    ['text', { size: 'hug', style: heading }, 'Projects'],
    ['text', { size: 'hug', style: note }, 'Typed into the table itself: in Edit, double-click a cell to change it. Grouped by who leads the work.'],
    ['table', {
      name: 'projects', label: 'Projects', group: 'lead', borders: 'grid', density: 'compact',
      columns: [
        { key: 'project', label: 'Project', width: 170, bold: true },
        { key: 'progress', label: 'Progress', show: 'progress', width: 130 },
        { key: 'onTrack', label: 'On track', show: 'check', align: 'center' },
        { key: 'rating', label: 'Client rating', show: 'stars' },
        { key: 'site', label: 'Site', show: 'link' },
        { key: 'hours', label: 'Hours', format: 'int', align: 'end', total: 'sum' },
        { key: 'budget', label: 'Budget', format: 'currency', align: 'end', total: 'sum', color: 'accent' },
        { key: 'lead', label: 'Lead' },
      ],
      value: [
        project('Packaging refresh', 'Mira', 1, true, 5, 'https://acme.example', 120, 4200),
        project('Patient app', 'Jonas', 0.55, true, 4, 'https://lumen.example', 340, 17400),
        project('Annual report', 'Mira', 0.8, true, 4, 'https://harbor.example', 96, 3150),
        project('Wayfinding signs', 'Ana', 0.35, false, 3, 'https://northfield.example', 64, 1900),
        project('Brand guidelines', 'Ana', 0.9, true, 5, 'https://kite.example', 150, 5400),
        project('Menu boards', 'Jonas', 0.2, false, 3, 'https://orbit.example', 22, 1250),
      ],
    }],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['table', {
        label: 'Day rates', borders: 'outer', density: 'roomy', header: 'strong', search: false,
        columns: [{ key: 'role', label: 'Role' }, { key: 'rate', label: 'Per day', format: 'currency', align: 'end' }],
        value: [{ role: 'Design lead', rate: 820 }, { role: 'Designer', rate: 640 }, { role: 'Developer', rate: 700 }, { role: 'Writer', rate: 560 }],
      }],
      ['chart', { type: 'bar', color: 'agent', label: 'Hours by project', size: 1.4 },
        ['map', { label: ['get', '$it', 'project'], value: ['get', '$it', 'hours'] }, '$projects']]],
    ['calendar', { size: 'hug', label: 'Due dates', week: 'sun', value: '2026-10-21' },
      ['map', { date: ['get', '$it', 'due'], title: ['get', '$it', 'client'], color: ['cond', ['=', ['get', '$it', 'status'], 'Paid'], 'live', ['=', ['get', '$it', 'status'], 'Overdue'], 'bad', 'accent'] }, '$invoices']],
    ['break'],
    ['text', { size: 'hug', style: heading }, 'House style'],
    ['text', { size: 'hug', style: note }, 'The same fonts, sizes and spacing the studio uses on paper. Each one is a text style in the panel on the right.'],
    ['row', { size: 'hug', style: { gap: 16 } },
      ['col', { style: { gap: 10 } },
        ['text', { style: eyebrow }, 'Label · Inter, caps, wide spacing'],
        ['text', { style: { font: 'playfair', size: 34, weight: 700, line: 1.1 } }, 'Display · Playfair'],
        ['text', { style: { font: 'lora', italic: true, size: 19, line: 1.5, border: 'l', bcolor: 'accent', bwidth: 3, pad: '4 0 4 16' } },
          'Good design is as little design as possible. A quote set in Lora.'],
        ['text', { style: { font: 'source-serif', size: 16, line: 1.7, para: 14, align: 'justify' } },
          'Body text in Source Serif, justified, with generous line height.\n\nParagraphs sit fourteen pixels apart, set by paragraph spacing rather than empty lines.']],
      ['col', { style: { gap: 10 } },
        ['text', { style: { font: 'fraunces', size: 48, weight: 800, tracking: -0.03, line: 1, fg: 'accent' } }, '{{billed | compact}}'],
        ['text', { style: { font: 'grotesk', size: 18, weight: 600, decor: 'underline' } }, 'Space Grotesk, underlined'],
        ['text', { style: { font: 'jetbrains', size: 13, bg: 'sunken', radius: 10, pad: '10 14', shadow: 'sm' } }, 'INV-2026-041 · JetBrains Mono'],
        ['list', { type: 'bullet', marker: 'arrow', density: 'compact', label: 'Next quarter' }, 'Raise day rates by 5%', 'Hire a second developer', 'Move invoices to the 1st of the month']]],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['list', { name: 'yearEnd', type: 'check', label: 'Before year end', density: 'roomy' },
        { text: 'Chase the overdue invoices', done: true }, 'Send the Q4 statements', 'Archive finished projects'],
      ['col', { size: 1.3 },
        ['canvas', { name: 'approval', label: 'Approved by', paper: 'lines', color: 'accent' }],
        ['text', { size: 'hug', style: { font: 'caveat', size: 24, fg: ['if', ['empty?', '$approval'], 'faint', 'accent'] } },
          '{{(if (empty? approval) "Waiting for a signature" "Thanks — approved!")}}']]]],
};

export const TEMPLATES: Template[] = [showcase, tables, quote, savings, feedback];
