// Starting points, written in the same notation an agent uses.

import type { Json } from './types';

export interface Template {
  id: string;
  title: string;
  about: string;
  meta?: Record<string, Json>;
  root: Json;
}

const label = { fg: 'muted', size: 13 };
const card = { bg: 'sunken', radius: 12, pad: 8 };

const line = (what: string, qty: number, price: number): Json => [
  'row', { size: 'hug', style: { border: 'b' } },
  ['input', { type: 'text', value: what, placeholder: 'Describe the work', size: 3 }],
  ['input', { type: 'number', value: qty, min: 0, style: { align: 'end' } }],
  ['input', { type: 'number', value: price, min: 0, step: 5, style: { align: 'end' } }],
  ['formula', { format: 'currency', style: { align: 'end', valign: 'center' } }, ['*', ['sib', 1], ['sib', 2]]],
];

const quote: Template = {
  id: 'quote',
  title: 'Quote',
  about: 'Line items that add up, a discount slider, and a button that saves each quote.',
  meta: { currency: 'EUR' },
  root: ['col',
    ['row', { size: 'hug' },
      ['col', { size: 2 },
        ['text', { style: { size: 34, weight: 750 } }, 'Quote'],
        ['text', { style: { fg: 'muted' } }, 'Prepared for **{{(default client "your client")}}** on {{date | date}}']],
      ['col',
        ['icon', { style: { fg: 'accent', size: 30, align: 'end' } }, 'anchor'],
        ['text', { style: { align: 'end', fg: 'muted', size: 13 } }, '**Northwind Studio**\n12 Harbour Lane, Bristol']]],
    ['row', { size: 'hug' },
      ['input', { name: 'client', type: 'text', label: 'Client', value: 'Ada Lovelace', size: 2 }],
      ['input', { name: 'date', type: 'date', label: 'Date', value: '2026-09-30' }],
      ['input', { name: 'valid', type: 'number', label: 'Valid for (days)', value: 30, min: 1 }]],
    ['row', { size: 'hug', style: { fg: 'muted', size: 12, weight: 600, border: 'b' } },
      ['text', { size: 3 }, 'Item'],
      ['text', { style: { align: 'end' } }, 'Qty'],
      ['text', { style: { align: 'end' } }, 'Unit price'],
      ['text', { style: { align: 'end' } }, 'Amount']],
    ['col', { name: 'lines', size: 'hug' },
      line('Brand identity', 1, 2400),
      line('Website design, per page', 6, 380),
      line('Photography day', 2, 650)],
    ['row', { size: 'hug' },
      ['col', { size: 3 },
        ['row', { size: 'hug' },
          ['button', { size: 'hug', variant: 'soft', do: ['dup!', ['child', 'lines', -1]] }, 'Add a line'],
          ['button', { size: 'hug', variant: 'ghost', do: ['remove!', ['child', 'lines', -1]], hidden: ['<=', ['len', '$lines'], 1] }, 'Remove the last'],
          ['empty']],
        ['text', { style: label }, 'Valid until {{(date+ date valid) | date}}.']],
      ['col', { size: 2 },
        ['row', 'Subtotal', ['formula', { name: 'subtotal', format: 'currency', style: { align: 'end' } }, ['sum', ['column', '$lines', 3]]]],
        ['row',
          ['input', { name: 'discount', type: 'slider', min: 0, max: 30, step: 1, value: 10, label: 'Discount {{discount}}%' }],
          ['formula', { name: 'off', format: 'currency', style: { align: 'end', valign: 'end', fg: 'live' } }, ['-', ['*', '$subtotal', ['/', '$discount', 100]]]]],
        ['row', 'VAT 19%', ['formula', { name: 'vat', format: 'currency', style: { align: 'end' } }, ['*', ['+', '$subtotal', '$off'], 0.19]]],
        ['row', { style: { border: 't', weight: 700, size: 18 } },
          'Total',
          ['formula', { name: 'total', format: 'currency', style: { align: 'end' } }, ['+', '$subtotal', '$off', '$vat']]]]],
    ['row', { size: 'hug', style: { ...card, pad: 6 } },
      ['button', { do: ['insert!', 'quotes', { client: '$client', date: '$date', items: ['len', '$lines'], total: '$total' }] }, 'Save this quote'],
      ['text', { size: 3, style: { fg: 'muted', valign: 'center' } },
        '{{(len (rows "quotes"))}} saved so far, worth {{(sum (column (rows "quotes") "total")) | currency}}.']],
  ],
};

const savings: Template = {
  id: 'savings',
  title: 'Savings plan',
  about: 'Sliders feed a function held in a cell; a chart and three totals follow.',
  root: ['col', { style: { gap: 6 } },
    ['text', { size: 'hug', style: { size: 30, weight: 750 } }, 'Savings plan'],
    ['text', { size: 'hug', style: { fg: 'muted' } }, 'Move the sliders. Everything on the right follows.'],
    ['row', { style: { gap: 10 } },
      ['col', { size: 2, style: card },
        ['input', { name: 'monthly', type: 'slider', min: 50, max: 2000, step: 50, value: 400, label: 'Every month I save {{monthly | currency}}' }],
        ['input', { name: 'years', type: 'slider', min: 1, max: 40, step: 1, value: 15, label: 'For {{years}} years' }],
        ['input', { name: 'rate', type: 'slider', min: 0, max: 12, step: 0.5, value: 6, label: 'Earning {{rate}}% a year' }],
        ['input', { name: 'start', type: 'number', min: 0, step: 500, value: 5000, label: 'Starting with' }],
        ['formula', { name: 'balance', hidden: true },
          ['fn', ['y'],
            ['let', ['r', ['/', '$rate', 1200], 'n', ['*', '$y', 12]],
              ['if', ['=', '$r', 0],
                ['+', '$start', ['*', '$monthly', '$n']],
                ['+', ['*', '$start', ['^', ['+', 1, '$r'], '$n']],
                  ['*', '$monthly', ['/', ['-', ['^', ['+', 1, '$r'], '$n'], 1], '$r']]]]]]]],
      ['col', { size: 3 },
        ['row', { size: 'hug' },
          ['col',
            ['text', { style: label }, 'After {{years}} years'],
            ['formula', { name: 'final', format: 'currency', style: { size: 24, weight: 750, fg: 'accent' } }, ['balance', '$years']]],
          ['col',
            ['text', { style: label }, 'You put in'],
            ['formula', { name: 'paid', format: 'currency', style: { size: 20, weight: 600 } }, ['+', '$start', ['*', '$monthly', '$years', 12]]]],
          ['col',
            ['text', { style: label }, 'Growth'],
            ['formula', { name: 'growth', format: 'currency', style: { size: 20, weight: 600, fg: 'live' } }, ['-', '$final', '$paid']]]],
        ['chart', { type: 'area', label: 'Balance by year' },
          ['map', { label: ['str', '$it'], value: ['round', ['balance', '$it']] }, ['range', 0, ['+', '$years', 1]]]],
        ['text', { size: 'hug', style: label },
          'Growth makes up {{(/ growth final) | percent}} of the final amount.{{(if (> rate 8) " A return above 8% a year is optimistic." "")}}']]],
  ],
};

const feedback: Template = {
  id: 'feedback',
  title: 'Feedback form',
  about: 'A form that saves answers to a collection, next to live results drawn from it.',
  root: ['row', { style: { gap: 12 } },
    ['col',
      ['text', { size: 'hug', style: { size: 26, weight: 750 } }, 'How was your visit?'],
      ['input', { name: 'who', type: 'text', label: 'Your name', placeholder: 'Name', size: 'hug' }],
      ['input', { name: 'stars', type: 'rating', label: 'Rating', value: 4, max: 5, size: 'hug' }],
      ['input', { name: 'topic', type: 'select', label: 'What is this about?', options: ['list', 'Food', 'Service', 'Atmosphere'], value: 'Food', size: 'hug' }],
      ['input', { name: 'comment', type: 'textarea', label: 'Anything to add?', placeholder: 'Optional' }],
      ['button', {
        size: 'hug',
        do: ['do',
          ['insert!', 'feedback', { name: ['default', '$who', 'Anonymous'], rating: '$stars', topic: '$topic', comment: '$comment' }],
          ['set!', 'who', ''],
          ['set!', 'comment', '']],
      }, 'Send feedback']],
    ['col', { style: card },
      ['text', { size: 'hug', style: { size: 18, weight: 650 } }, 'Answers so far'],
      ['row', { size: 'hug' },
        ['col',
          ['formula', { name: 'answers', style: { size: 30, weight: 750 } }, ['len', ['rows', 'feedback']]],
          ['text', { style: label }, 'answers']],
        ['col',
          ['formula', {
            name: 'mean', format: '0.0',
            style: { size: 30, weight: 750, fg: ['cond', ['=', '$answers', 0], 'faint', ['>=', '$mean', 4], 'live', ['>=', '$mean', 3], 'warn', 'bad'] },
          }, ['avg', ['column', ['rows', 'feedback'], 'rating']]],
          ['text', { style: label }, 'average rating']]],
      ['chart', { type: 'bar', label: 'How many gave each rating' },
        ['map', ['fn', ['s'], { label: ['str', '$s', '★'], value: ['len', ['where', ['rows', 'feedback'], 'rating', '$s']] }], ['range', 1, 6]]],
      ['table', ['map', { name: ['get', '$it', 'name'], rating: ['get', '$it', 'rating'], topic: ['get', '$it', 'topic'], when: ['fmt', ['get', '$it', 'at'], 'ago'] },
        ['take', 5, ['reverse', ['rows', 'feedback']]]]]],
  ],
};

export const tour: Template = {
  id: 'tour',
  title: 'Start here',
  about: 'A short tour you can poke at.',
  root: ['col', { style: { gap: 10 } },
    ['row', { size: 'hug' },
      ['col', { size: 3 },
        ['text', { style: { size: 34, weight: 750, line: 1.1 } }, 'Every document starts as one cell'],
        ['text', { style: { fg: 'muted', size: 16 } },
          'Select a cell and press a **+** on its edge to split it. Hold Shift to select several, then merge them. A cell can hold text, an input, a formula, a picture, an icon, a button, a chart or a table.']],
      ['image', { fit: 'contain', alt: 'One cell dividing into two', size: 2 }, '/art/division.svg']],
    ['row', { size: 'hug', style: { gap: 10 } },
      ['col', { style: card },
        ['text', '**Cells hold values**'],
        ['input', { name: 'apples', type: 'slider', min: 0, max: 24, value: 6, label: '{{apples}} apples' }],
        ['input', { name: 'each', type: 'number', value: 0.45, step: 0.05, min: 0, label: 'Price of one' }]],
      ['col', { style: { ...card, bg: 'accent-soft' } },
        ['text', '**Formulas read other cells**'],
        ['formula', { name: 'cost', format: 'currency', style: { size: 34, weight: 750, fg: 'accent' } }, ['*', '$apples', '$each']],
        ['text', { style: label }, 'This one is `(* apples each)`. Select it to see what it reads.']],
      ['col', { style: card },
        ['text', '**Buttons change things**'],
        ['row', { size: 'hug' },
          ['button', { size: 'hug', do: ['set!', 'apples', ['+', '$apples', 1]] }, 'Add an apple'],
          ['button', { size: 'hug', variant: 'ghost', do: ['set!', 'apples', 0] }, 'Eat them all']],
        ['text', { style: label }, '{{(if (= apples 0) "The basket is empty." (str apples " in the basket, " (fmt cost "currency") " to pay."))}}']]],
    ['row', { size: 'hug' },
      ['icon', { style: { fg: 'agent', size: 26, valign: 'start' } }, 'sparkles'],
      ['text', { size: 12 },
        '**An agent can work here with you.** Everything you do is a small instruction such as `(split c4 row)`, and an agent sends the same instructions. Open **Activity** to watch them arrive, or to leave the agent a message.']],
    ['text', { size: 'hug', style: label },
      'Enter edits a cell. / changes what it holds. ⌥ with an arrow splits. ⌘M merges. ⌫ clears, then removes. ⌘Z undoes.'],
  ],
};

export const TEMPLATES: Template[] = [quote, savings, feedback];
